Likha/core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('login', views.SignInView.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),

    # nutritionist view
    path('nutritionist', views.nutritionist, name='nutritionist'),

]

Likha/datacollection/urls.py
from django.urls import path
from . import views

app_name = 'data-collection'

urlpatterns = [
    path('', views.index_bns, name='index'),

    # for nutritionists,
    path('nutritionist', views.nutritionist_data_input, name='nutritionist-input'),

    # index of nutritional statuses
    path('nutritional-status', views.nutritional_status, name='nutritional-status'),

    # fhsis index
    path('fhsis', views.fhsis_index, name='fhsis'),

    # create FHSIS
    path('fhsis/create', views.create_fhsis, name='create-fhsis'),

    # encode NS
    path('nutritional-status/input', views.encode_nutritional_statuses, name='encode-ns'),
    # put NS to DB
    path('nutritional-status/store', views.store_nutritional_statuses, name='store-ns'),

    # encode Child Care
    path('input/child-care', views.encode_child_care, name='encode-cc'),
    # put child care to db
    path('store/child-care', views.store_child_care, name='store-cc'),

    # encode Immunization
    path('input/immunization', views.encode_immunization, name='encode-immunization'),
    # put immunization to db
    path('store/immunization', views.store_immunization, name='store-immunization'),

    # encode TB
    path('input/tuberculosis', views.encode_tuberculosis, name='encode-tb'),
    path('store/tuberculosis', views.store_tuberculosis, name='store-tb'),

    # encode malaria
    path('input/malaria', views.encode_malaria, name='encode-malaria'),
    path('store/malaria', views.store_malaria, name='store-malaria'),

    # encode flariasis
    path('input/flariasis', views.encode_flariasis, name='encode-flariasis'),
    path('store/flariasis', views.store_flariasis, name='store-flariasis'),

    # encode schistosomiasis
    path('input/schistosomiasis', views.encode_schistosomiasis, name='encode-schistosomiasis'),
    path('store/schistosomiasis', views.store_schistosomiasis, name='store-schistosomiasis'),

    # encode leprosy
    path('input/leprosy', views.encode_leprosy, name='encode-leprosy'),
    path('store/leprosy', views.store_leprosy, name='store-leprosy'),

    # maternal
    path('input/maternal', views.encode_maternal, name='encode-maternal'),

    # sti surveillance
    path('input/sti_surveillance', views.encode_sti_surveillance, name='encode-sti'),

    # EXTERNAL DATA

    # external data input
    path('external_data/', views.input_external_data, name='input-external'),

    # input health care waste management
    path('external_data/hcwm/input/', views.encode_health_care_waste_management, name='encode-healthcare'),

    # informal settlers
    path('external_data/informal_settlers/input', views.encode_informal_settlers, name='encode-informal-settlers'),

    # unemployment rate
    path('external_data/unemployment_rate/input', views.encode_unemployment_rate, name='encode-ur'),


]

Likha/datacollection/forms.py
from django import forms
from .models import STISurveillance, Maternal, HealthCareWasteManagement, InformalSettlers, UnemploymentRate


class MaternalForm(forms.ModelForm):

    class Meta:
        model = Maternal
        fields = '__all__'
        exclude = ('fhsis',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })


class STISurveillanceForm(forms.ModelForm):

    class Meta:
        model = STISurveillance
        fields = '__all__'
        exclude = ('fhsis',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })


class HealthCareWasteManagementForm(forms.ModelForm):

    class Meta:
        model = HealthCareWasteManagement
        fields = '__all__'
        exclude = ('date',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })


class InformalSettlersForm(forms.ModelForm):

    class Meta:
        model = InformalSettlers
        fields = '__all__'
        exclude =('date',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })


class UnemploymentRateForm(forms.ModelForm):

    class Meta:
        model = UnemploymentRate
        fields = '__all__'
        exclude = ('date',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })

Likha/datacollection/views.py
import datetime
from datetime import datetime as dt
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from datacollection.forms import MaternalForm, STISurveillanceForm, HealthCareWasteManagementForm, InformalSettlersForm, \
    UnemploymentRateForm
from .models import NutritionalStatus, AgeGroup, Barangay, OperationTimbang, OPTValues, ChildCare, FHSIS, Immunization, \
    Tuberculosis, Malaria, Flariasis, Leprosy, Schistosomiasis, Maternal, STISurveillance
from helpers import global_user, checkers, functions


# Create your views here.
@login_required
def index_bns(request):
    return render(request, 'datacollection/index_bns.html', None)


@login_required
def nutritionist_data_input(request):
    return render(request, 'datacollection/nutritionists-data-input.html', None)


@login_required
def nutritional_status(request):

    month = datetime.datetime.now().month
    year = datetime.datetime.now().year
    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    try:
        OperationTimbang.objects.get(date__month=month, date__year=year, barangay=barangay)
        has_opt = True
    except OperationTimbang.DoesNotExist:
        has_opt = False

    print(has_opt)

    context = {
        'has_opt': has_opt
    }

    return render(request, 'datacollection/ns_index.html', context)


@login_required
def fhsis_index(request):

    month = datetime.datetime.now().month
    year = datetime.datetime.now().year
    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    # FHSIS fields

    has_maternal = checkers.check_fhsis(month, year, barangay, Maternal)
    has_immunization = checkers.check_fhsis(month, year, barangay, Immunization)
    has_malaria = checkers.check_fhsis(month, year, barangay, Malaria)
    has_tb = checkers.check_fhsis(month, year, barangay, Tuberculosis)
    has_schisto = checkers.check_fhsis(month, year, barangay, Schistosomiasis)
    has_flariasis = checkers.check_fhsis(month, year, barangay, Flariasis)
    has_leprosy = checkers.check_fhsis(month, year, barangay, Leprosy)
    has_cc = checkers.check_fhsis(month, year, barangay, ChildCare)
    has_sti = checkers.check_fhsis(month, year, barangay, STISurveillance)

    try:
        FHSIS.objects.get(date__month=month, date__year=year, barangay=barangay)
        has_fhsis = True
    except FHSIS.DoesNotExist:
        has_fhsis = False

    print(has_maternal)

    context = {
        'has_fhsis': has_fhsis,
        'has_maternal': has_maternal,
        'has_immunization': has_immunization,
        'has_malaria': has_malaria,
        'has_tb': has_tb,
        'has_schisto': has_schisto,
        'has_flariasis': has_flariasis,
        'has_leprosy': has_leprosy,
        'has_cc': has_cc,
        'has_sti': has_sti
    }

    return render(request, 'datacollection/fhsis_index.html', context)


# manually encode views here
@login_required
def encode_nutritional_statuses(request):

    nutritional_statuses = NutritionalStatus.objects.all()
    age_groups = AgeGroup.objects.all()
    barangays = Barangay.objects.all()

    context = {
        'nutritional_statuses': nutritional_statuses,
        'age_groups': age_groups,
        'barangays': barangays
    }

    return render(request, 'datacollection/input_nutritional_statuses.html', context)


# Child Care encode
@login_required
def encode_child_care(request):

    return functions.encode_fhsis(request, ChildCare, 'data-collection:store-cc', "Child Care")


# encode Immunization
@login_required
def encode_immunization(request):

    return functions.encode_fhsis(request, Immunization, 'data-collection:store-immunization', "Immunization")


# encode Flariasis
@login_required
def encode_flariasis(request):

    return functions.encode_fhsis(request, Flariasis, 'data-collection:store-flariasis', "Flariasis")


# encode Leprosy
@login_required
def encode_leprosy(request):

    return functions.encode_fhsis(request, Leprosy, 'data-collection:store-leprosy', "Leprosy")


# encode Schistosomiasis
@login_required
def encode_schistosomiasis(request):

    return functions.encode_fhsis(request, Schistosomiasis, 'data-collection:store-schistosomiasis', "Schistosomiasis")


# encode Tuberculosis
@login_required
def encode_tuberculosis(request):

    return functions.encode_fhsis(request, Tuberculosis, 'data-collection:store-tb', "Tuberculosis")


# encode Malaria
@login_required
def encode_malaria(request):

    return functions.encode_fhsis(request, Malaria, 'data-collection:store-malaria', "Malaria")


# VIEWS that store the data to the DB
@login_required
def store_nutritional_statuses(request):

    if checkers.validate_fields(request) > 0:
        messages.error(request, 'Please fill up all fields or enter valid inputs only')
        return redirect('data-collection:encode-ns')

    current_user = global_user.get_user(request.user.username)
    barangay = current_user.barangay

    opt = OperationTimbang(barangay=barangay)
    opt.save()

    for key, value in request.POST.items():
        if key == 'barangay' or key == 'csrfmiddlewaretoken':
            continue

        splits = key.split('-')

        ns_code = splits[0]
        ag_code = splits[1]
        sex_code = splits[2]

        nutritional_status = NutritionalStatus.objects.get(code=ns_code)
        age_group = AgeGroup.objects.get(code=ag_code, sex=sex_code)
        number = float(value)

        OPTValues.objects.create(
            opt=opt,
            nutritional_status=nutritional_status,
            age_group=age_group,
            values=number
        )

    messages.success(request, 'Nutritional statuses successfully encoded!')
    return redirect('data-collection:index')


@login_required
def store_child_care(request):

    url = 'data-collection:encode-cc'

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.fhsis_input(request, url, ChildCare, "Child Care", barangay)


@login_required
def store_immunization(request):

    url = 'data-collection:encode-immunization'

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.fhsis_input(request, url, Immunization, "Immmunization", barangay)


@login_required
def store_tuberculosis(request):

    url = 'data-collection:encode-tb'

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.fhsis_input(request, url, Tuberculosis, "Tuberculosis", barangay)


@login_required
def store_malaria(request):

    url = 'data-collection:encode-malaria'

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.fhsis_input(request, url, Malaria, "Malaria", barangay)


@login_required
def store_flariasis(request):

    url = 'data-collection:encode-flariasis'

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.fhsis_input(request, url, Flariasis, "Flariasis", barangay)


@login_required
def store_leprosy(request):

    url = 'data-collection:encode-leprosy'

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.fhsis_input(request, url, Leprosy, "Leprosy", barangay)


@login_required
def store_schistosomiasis(request):

    url = 'data-collection:encode-schistosomiasis'

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.fhsis_input(request, url, Schistosomiasis, "Schistosomiasis", barangay)


@login_required
def create_fhsis(request):

    user = global_user.get_user(request.user.username)

    FHSIS.objects.create(
        barangay=user.barangay
    )

    month = datetime.datetime.now().strftime("%B")

    messages.success(request, "FHSIS generated for " + str(month))
    return redirect('data-collection:fhsis')


# STI Surveillance and Maternal

@login_required
def encode_maternal(request):

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.input_fhsis(request, MaternalForm, "Maternal", barangay)


@login_required
def encode_sti_surveillance(request):

    bns = global_user.get_user(request.user.username)
    barangay = bns.barangay

    return functions.input_fhsis(request, STISurveillanceForm, "STI Surveillance", barangay)


# EXTERNAL DATA INPUT BY NUTRITIONISTS

@login_required
def input_external_data(request):

    context = {

    }

    return render(request, 'datacollection/input_external_data.html', context)


@login_required
def encode_health_care_waste_management(request):

    return functions.input_external_data(request, HealthCareWasteManagementForm, "Health Care Waste Management")


@login_required
def encode_informal_settlers(request):

    return functions.input_external_data(request, InformalSettlersForm, "Informal Settlers")


@login_required
def encode_unemployment_rate(request):

    return functions.input_external_data(request, UnemploymentRateForm, "Unemployment Rate")

Likha/templates/datacollection/encode_external_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Encode {{ data }}</title>

    {% load static %}

    {% include 'bootstrap.html' %}
</head>
<body>

    {% include 'messages.html' %}
    {% include 'temporary_navbar.html' %}

    <div class="container">
        <h1>Encode {{ data }}</h1>

        <form method="POST">
            {% csrf_token %}

            {% include 'form_template.html' %}

            <div align="center">
                <button class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</body>
</html>

Likha/templates/datacollection/encode_fhsis.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Encode {{ data }}</title>

    {% load static %}

    {% include 'bootstrap.html' %}
</head>
<body>

    {% include 'temporary_navbar.html' %}
    {% include 'messages.html' %}

    <div class="container">
        <h1>Encode {{ data }}</h1>

        <form method="POST">
            {% csrf_token %}

            {% include 'form_template.html' %}

            <div align="center">
                <button class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</body>
</html>

Likha/templates/datacollection/fhsis_data_input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Input</title>

    {% load static %}

    {% include 'bootstrap.html' %}

</head>
<body>
    {% include 'temporary_navbar.html' %}
    {% include 'messages.html' %}

    <div class="container">
        <h1>Encode {{ data }}</h1>

        <form method="POST" action="{{ url }}">
            {% csrf_token %}
            <table class="table">
                <tr>
                    <td>-</td>

                {% for x in age_groups %}
                    <td>{{ x.name }} - {{ x.sex }}</td>
                {% endfor %}
                </tr>

            {% for x in fields %}
                <tr>
                    <td>{{ x.field.verbose_name }}</td>
                    {% for y in age_groups %}
                        <td>
                            <div class="form-group">
                                <input class="form-control" type="number" minlength="0"
                                 name="{{ y.code }}-{{ x.string }}-{{ y.sex }}" step="0.01">
                            </div>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </table>
            <button type="submit" class="btn btn-block btn-primary mb-5">Submit</button>
        </form>
    </div>
</body>
</html>

Likha/templates/datacollection/fhsis_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FHSIS</title>
    {% load static %}

    {% include 'bootstrap.html' %}
</head>
<body>

    {% include 'messages.html' %}
    {% include 'temporary_navbar.html' %}
    <div class="container">
        <h1>FHSIS</h1>
        {% if has_fhsis %}
             <p>Status:
                <span class="text-success">FHSIS already created</span>
             </p>

            <p>Upload File</p>
            <h3>Input Data</h3>
            <table class="table">
                <tr>
                    <th>Data</th>
                    <th>Action</th>
                    <th>Status</th>
                </tr>
                <tr>
                    <td>Maternal Care</td>
                    {% if has_maternal %}
                        <td>
                            <a href="{% url 'data-collection:encode-maternal' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-maternal' %}">
                                <button class="btn btn-primary">Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Immunization</td>
                    {% if has_immunization %}
                        <td>
                            <a href="{% url 'data-collection:encode-immunization' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-immunization' %}">
                                <button class="btn btn-primary">Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Malaria</td>
                    {% if has_malaria %}
                        <td>
                            <a href="{% url 'data-collection:encode-malaria' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-malaria' %}">
                                <button class="btn btn-primary">Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Tuberculosis</td>
                    {% if has_tb %}
                        <td>
                            <a href="{% url 'data-collection:encode-tb' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-tb' %}">
                                <button class="btn btn-primary">Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Schistosomiasis</td>
                    {% if has_schisto %}
                        <td>
                            <a href="{% url 'data-collection:encode-schistosomiasis' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-schistosomiasis' %}">
                                <button class="btn btn-primary" >Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Flariasis</td>
                    {% if has_flariasis %}
                        <td>
                            <a href="{% url 'data-collection:encode-flariasis' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-flariasis' %}">
                                <button class="btn btn-primary">Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Leprosy</td>
                    {% if has_leprosy %}
                        <td>
                            <a href="{% url 'data-collection:encode-leprosy' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-leprosy' %}">
                                <button class="btn btn-primary">Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Child Care</td>
                    {% if has_cc %}
                        <td>
                            <a href="{% url 'data-collection:encode-cc' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-cc' %}">
                                <button class="btn btn-primary">Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>STI Surveillance</td>
                    {% if has_sti %}
                        <td>
                            <a href="{% url 'data-collection:encode-sti' %}">
                                <button class="btn btn-primary disabled" disabled>Encode</button>
                            </a>
                        </td>
                        <td class="text-success">Already encoded for this month</td>
                    {% else %}
                        <td>
                            <a href="{% url 'data-collection:encode-sti' %}">
                                <button class="btn btn-primary">Encode</button>
                            </a>
                        </td>
                        <td class="text-warning">Not yet encoded</td>
                    {% endif %}
                </tr>
            </table>
        {% else %}
            <p>Status:
                <span class="text-danger">FHSIS not yet created</span>
            </p>
            <a href="{% url 'data-collection:create-fhsis' %}">Create FHSIS</a>
        {% endif %}

        <!-- TODO -->
    </div>
</body>
</html>

Likha/templates/datacollection/index_bns.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Data Collection</title>

    {% include 'bootstrap.html' %}

</head>
<body>

    {% include 'temporary_navbar.html' %}
    {% include 'messages.html' %}

    <div class="container">
        <a href="{% url 'data-collection:nutritional-status' %}">Nutritional Statuses</a>
        <a href="{% url 'data-collection:fhsis' %}">FHSIS</a>
    </div>
</body>
</html>

Likha/templates/datacollection/input_external_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Input External Data</title>

    {% load static %}

    {% include 'bootstrap.html' %}

</head>
<body>

    {% include 'messages.html' %}
    {% include 'temporary_navbar.html' %}

    <div class="container">
        <h1>Input External Data</h1>

        <table class="table">
            <tr>
                <th>Data</th>
                <th>Action</th>
                <th>Status</th>
            </tr>

            <tr>
                <td>Health Care Waste Management</td>
                <td>
                    <a href="{% url 'data-collection:encode-healthcare' %}">
                        <button class="btn btn-primary">Encode</button>
                    </a>
                </td>
                <td>TODO</td>
            </tr>

            <tr>
                <td>Informal Settlers</td>
                <td>
                    <a href="{% url 'data-collection:encode-informal-settlers' %}">
                        <button class="btn btn-primary">Encode</button>
                    </a>
                </td>
                <td>TODO</td>
            </tr>

            <tr>
                <td>Unemployment Rate</td>
                <td>
                    <a href="{% url 'data-collection:encode-ur' %}">
                        <button class="btn btn-primary">Encode</button>
                    </a>
                </td>
                <td>TODO</td>
            </tr>
        </table>
    </div>

</body>
</html>

Likha/templates/datacollection/input_nutritional_statuses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Encode Nutritional Statuses</title>

    {% load static %}
    {% include 'bootstrap.html' %}

    <link rel="{% static 'css/input-ns.css' %}">

</head>
<body>
    {% include 'temporary_navbar.html' %}
    {% include 'messages.html' %}

    <div class="container">
        <h1>Encode Nutritional Statuses</h1>
{#        <form method="POST"  action="{% url 'data-collection:store-ns' %}">#}
{#            {% csrf_token %}#}
{##}
{#            <div class="form-group">#}
{#                <div class="form-group mt-5">#}
{#                    {% for nutritional_status in nutritional_statuses %}#}
{#                        <h3 class="mt-5">{{ nutritional_status.name }}</h3>#}
{#                        {% for age_group in age_groups %}#}
{#                            <label>{{ age_group.name }} - {{ age_group.sex }}</label>#}
{#                            <input type="number" class="form-control"#}
{#                                   name="{{ nutritional_status.code }}-{{ age_group.code }}-{{ age_group.sex }}">#}
{#                        {% endfor %}#}
{#                    {% endfor %}#}
{##}
{#                    <button type="submit" class="btn btn-primary mt-3 btn-block">Submit</button>#}
{#                </div>#}
{#            </div>#}
{#        </form>#}

        <form method="POST" action="{% url 'data-collection:store-ns' %}">
            {% csrf_token %}
            <table class="table">
                <tr>
                    <td>-</td>
                {% for x in age_groups %}
                    <td>{{ x.name }} - {{ x.sex }}</td>
                {% endfor %}
                </tr>

                {% for x in nutritional_statuses %}
                    <tr>
                        <td>{{ x.name }}</td>
                        {% for y in age_groups %}
                            <td>
                                <div class="form-group">
                                    <input class="form-control" type="number" minlength="0" name="{{ x.code }}-{{ y.code }}-{{ y.sex }}">
                                </div>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" class="btn btn-block btn-primary mb-5">Submit</button>
        </form>
    </div>
</body>
</html>

Likha/templates/datacollection/ns_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nutritional Statuses</title>
    {% load static %}

    {% include 'bootstrap.html' %}
</head>
<body>

    {% include 'messages.html' %}
    {% include 'temporary_navbar.html' %}

    <div class="container">
        <h1>Nutritional Statuses</h1>

        <p>Status:
            {% if has_opt %}
                <span class="text-success">Already encoded</span>
            {% else %}
                <span class="text-warning">Not yet encoded</span>
            {% endif %}
        </p>

        <a href="{% url 'data-collection:encode-ns' %}">Encode Manually</a>
        <a>Upload File</a>
    </div>
</body>
</html>