Likha/core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('login', views.SignInView.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),

    # nutritionist view
    path('nutritionist', views.nutritionist, name='nutritionist'),

]

Likha/templates/bootstrap.html
{#CSS#}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">


{# JS #}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

Likha/templates/form_template.html
{% if error %}
    <div class="alert alert-danger">
        <strong>{{ error }}</strong>
    </div>
{% endif %}


{% if form.errors %}
    <div class="alert-danger alert">
    {% for field in form %}
        <strong>{{ field.errors }}</strong>
    {% endfor %}
    </div>

{% endif %}


{% for field in form %}
    <div class="form-group">
        <label> {{ field.label_tag }}</label>
        {{ field }}
    </div>
{% endfor %}

Likha/templates/messages.html
{% comment %}
success or error message
{% endcomment %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} text-center" role="alert">
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
{% endif %}

Likha/templates/temporary_navbar.html
<div>
    <a href="{% url 'core:logout' %}">Logout</a>
</div>